### ISSUE TITLE
RealmSwift version error

### ISSUE THREAD

**Issue by gcohen-dev** [aheze/OpenFind#10]
I have an idea of contribute to this project for a long time now, 
But when I'm running this project on Xcode 15.4 I'm getting the following error:

```
Compiled module was created by a different version of the compiler ''; rebuild 'RealmSwift' and try again: 
```

Seems like it cannot handle the RealmSwift binary data which lays in the resources, any ideas?

**Comment by aheze** [comment]
This is because I downloaded the static library from the realmswift repo
back in like 2022, when it was swift 5.0 or something. Now it’s outdated
and I need to download it for swift 6.0 I think. It should be the latest
release:
https://github.com/realm/realm-swift/releases/tag/v10.53.0


Alternatively we could use realmswift via swift package manager. Saves a
big hassle but makes compile time a lot slower

**Comment by gcohen-dev** [comment]
Yep, I've tried to remove the static library and use it in the package manager, still not working. 
Nevermind tho.
